import { TableHeader } from '~/components/VhpUI/typings';

export const tableHeaders: TableHeader[] = [
    {
        label: 'Room Number',
        field: 'zinr',
        name: 'zinr',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Arrangement Code',
        field: 'argt',
        name: 'argt',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Rate Code',
        field: 'ratecode',
        name: 'ratecode',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Currency',
        field: 'currency',
        name: 'currency',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Room Rate',
        field: 'c-zipreis',
        name: 'c-zipreis',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Adult',
        field: 'pax',
        name: 'pax',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Compliment',
        field: 'comch',
        name: 'comch',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Local Currency',
        field: ' c-localrate',
        name: ' c-localrate',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Room Revenue',
        field: 'c-lodging',
        name: 'c-lodging',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Breakfast Revenue',
        field: 'c-bfast',
        name: 'c-bfast',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Lunch',
        field: 'c-lunch',
        name: 'c-lunch',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Dinner',
        field: 'c-dinner',
        name: 'c-dinner',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Other Rev',
        field: 'c-misc',
        name: 'c-misc',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Fix Cost',
        field: 'fixcost',
        name: 'fixcost',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Total Rate',
        field: 't-rev',
        name: 't-rev',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Arrival',
        field: 'ankunft',
        name: 'ankunft',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Depature',
        field: 'abreise',
        name: 'abreise',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Bill No',
        field: 'rechnr',
        name: 'rechnr',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Guest Name',
        field: 'name',
        name: 'name',
        align: 'left',
        sortable: false,
    },
    {
        label: 'ExRate',
        field: 'ex-rate',
        name: 'ex-rate',
        align: 'left',
        sortable: false,
    },
    {
        label: 'F',
        field: 'fix-rate',
        name: 'fix-rate',
        align: 'left',
        sortable: false,
    },
];
