import { TableHeader } from '~/components/VhpUI/typings';

export const ResTableHeaders: TableHeader[] = [
  {
    label: 'Reservation Number',
    field: 'resnr',
    name: 'resnr',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Reservation Name',
    field: 'reser-name',
    name: 'reser-name',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Group Name',
    field: 'groupname',
    name: 'groupname',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Guest Name',
    field: 'resli-name',
    name: 'resli-name',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Arrival Date',
    field: 'ankunft',
    name: 'ankunft',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Due Date',
    field: 'limitdate',
    name: 'limitdate',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Deposit',
    field: 'depositgef',
    name: 'depositgef',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Balance',
    field: 'balance',
    name: 'balance',
    align: 'right',
    sortable: true,
  },
  // {
  //   label: 'Deposit Paid',
  //   field: 'paid',
  //   name: 'paid',
  //   align: 'right',
  //   sortable: true,
  // },
  // {
  //   label: 'Pay Date',
  //   field: 'paydate',
  //   name: 'paydate',
  //   align: 'right',
  //   sortable: true,
  // },
  // {
  //   label: 'Pay Article',
  //   field: 'payarticle',
  //   name: 'payarticle',
  //   align: 'right',
  //   sortable: true,
  // },
  // {
  //   label: 'Deposit Paid 2',
  //   field: 'paid2',
  //   name: 'paid2',
  //   align: 'right',
  //   sortable: true,
  // },
  { name: 'actions', field: 'actions' },
];
