import { TableHeader } from '~/components/VhpUI/typings';

export const tableHeadersRight: TableHeader[] = [
  {
    label: 'Reservation Number',
    field: 'resnr',
    name: 'resnr',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Room Number',
    field: 'rm',
    name: 'rm',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Reservation Name',
    field: 'resname',
    name: 'resname',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Guest Name',
    field: 'name',
    name: 'name',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Arrival',
    field: 'ankufat',
    name: 'ankufat',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Departure',
    field: 'departure',
    name: 'departure',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Category',
    field: 'cat',
    name: 'cat',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Adult',
    field: 'adult',
    name: 'adult',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Compliment',
    field: 'comp',
    name: 'comp',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Status',
    field: 'status',
    name: 'status',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Arrangment Code',
    field: 'ac',
    name: 'ac',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Room Rate',
    field: 'rate',
    name: 'rate',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Group Name',
    field: 'gname',
    name: 'gname',
    align: 'right',
    sortable: true,
  },
  { name: 'actions', field: 'actions' },
];
