import { TableHeader } from '~/components/VhpUI/typings';

export const ResTableHeaders: TableHeader[] = [
  {
    label: 'Reservation Number',
    field: 'resnr',
    name: 'resnr',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Reservation From',
    field: 'reser-name',
    name: 'reser-name',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Guest Name',
    field: 'resli-name',
    name: 'resli-name',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Arrival',
    field: 'ankunft',
    name: 'ankunft',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Departure',
    field: 'abreise',
    name: 'abreise',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Room Type',
    field: 'kurzbez',
    name: 'kurzbez',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Adult',
    field: 'erwachs',
    name: 'erwachs',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Compliment',
    field: 'gratis',
    name: 'gratis',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Reservation Status',
    field: 'resstatus',
    name: 'resstatus',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Arrangement Code',
    field: 'arrangement',
    name: 'arrangement',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Room Rate',
    field: 'zipreis',
    name: 'zipreis',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Group Name',
    field: 'groupname',
    name: 'groupname',
    align: 'left',
    sortable: true,
  },
  { name: 'actions', field: 'actions' },
];
