import { TableHeader } from '~/components/VhpUI/typings';

export const tableHeaders: TableHeader[] = [
  {
    label: 'Date',
    field: 'datum',
    name: 'datum',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Room Number',
    field: 'roomnumber',
    name: 'roomnumber',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Non Stay',
    field: 'nsflag',
    name: 'nsflag',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Master Bill',
    field: 'mbflag',
    name: 'mbflag',
    sortable: true,
  },
  {
    label: 'Shift',
    field: 'shift',
    name: 'shift',
    sortable: true,
  },
  {
    label: 'Bill Number',
    field: 'billno',
    name: 'billno',
    sortable: true,
  },
  {
    label: 'Article Number',
    field: 'artno',
    name: 'artno',
    sortable: true,
  },
  {
    label: 'Description',
    field: 'bezeich',
    name: 'bezeich',
    sortable: true,
  },
  {
    label: 'Voucher Number',
    field: 'voucher',
    name: 'voucher',
    sortable: true,
  },
  {
    label: 'Department',
    field: 'depart',
    name: 'depart',
    sortable: true,
  },
  {
    label: 'Outlet',
    field: 'outlet',
    name: 'outlet',
    sortable: true,
  },
  {
    label: 'Room Quantity',
    field: 'qty',
    name: 'qty',
    sortable: true,
  },
  {
    label: 'Amount',
    field: 'amount',
    name: 'amount',
    sortable: true,
  },
  {
    label: 'Guest Name',
    field: 'guestname',
    name: 'guestname',
    sortable: true,
  },
  {
    label: 'Bill Receiver',
    field: 'billrcvr',
    name: 'billrcvr',
    sortable: true,
  },
  {
    label: 'Time',
    field: 'zeit',
    name: 'zeit',
    sortable: true,
  },
  {
    label: 'ID',
    field: 'id',
    name: 'id',
    sortable: true,
  },
  {
    label: 'SYS Date',
    field: 'sysdate',
    name: 'sysdate',
    sortable: true,
  },
  {
    label: 'Remark',
    field: 'remark',
    name: 'remark',
    sortable: true,
  },
];
