import { TableHeader } from '~/components/VhpUI/typings';

export const tableHeaders: TableHeader[] = [
  {
    label: 'Reservation Number',
    field: 'resnr',
    name: 'resnr',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Reservation Name',
    field: 'resname',
    name: 'resname',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Group Name',
    field: 'gname',
    name: 'gname',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Guest Name',
    field: 'name',
    name: 'name',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Arrival',
    field: 'ankufat',
    name: 'ankufat',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Total Deposit',
    field: 'deposit',
    name: 'deposit',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Due Date',
    field: 'duedate',
    name: 'duedate',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Balance',
    field: 'balance',
    name: 'balance',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Deposit Paid',
    field: 'paid',
    name: 'paid',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Pay Date',
    field: 'paydate',
    name: 'paydate',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Pay Article',
    field: 'payarticle',
    name: 'payarticle',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Deposit Paid 2',
    field: 'paid2',
    name: 'paid2',
    align: 'right',
    sortable: true,
  },
  { name: 'actions', field: 'actions' },
];
