import { TableHeader } from '~/components/VhpUI/typings';

export const tableHeaders: TableHeader[] = [
  {
    label: 'Room Number',
    field: 'zinr',
    name: 'roomNumber',
    align: 'left',
    headerStyle: 'width: 100px',
    style: 'max-width: 100px',
    sortable: true,
  },
  {
    label: 'Status',
    field: 'fo-stat',
    name: 'statusFO',
    align: 'left',
    headerStyle: 'width: 80px',
    style: 'max-width: 80px',
    sortable: true,
  },
  {
    label: 'Adult',
    field: 'fo-ad',
    name: 'adultFO',
    align: 'center',
    headerStyle: 'width: 80px',
    style: 'max-width: 80px',
  },
  {
    label: 'Child',
    field: 'fo-ch1',
    name: 'childFO',
    align: 'center',
    headerStyle: 'width: 80px',
    style: 'max-width: 80px',
  },
  {
    label: 'Status',
    field: 'hk-stat',
    name: 'statusHK',
    align: 'left',
    headerStyle: 'width: 80px',
    style: 'max-width: 80px',
    sortable: true,
  },
  {
    label: 'Adult',
    field: 'hk-ad',
    name: 'adultHK',
    align: 'center',
    headerStyle: 'width: 80px',
    style: 'max-width: 80px',
  },
  {
    label: 'Child',
    field: 'hk-ch1',
    name: 'childHK',
    align: 'center',
    headerStyle: 'width: 80px',
    style: 'max-width: 80px',
  },
  {
    label: 'Explanation',
    field: 'explanation',
    name: 'explanation',
    align: 'left',
    sortable: true,
  },
];
