import { date } from 'quasar';
import { TableActionHeader } from '~/components/VhpUI/typings';

export const mainColumns: TableActionHeader[] = [
  {
    label: 'Date',
    classes: 'text-capitalize nowrap word-break',
    sortable: true,
    align: 'left',
    name: 'date',
    field: 'date',
    style: 'width: 100px',
    format: (t) => (t instanceof Date ? date.formatDate(t, 'YYYY/MM/DD') : '-'),
  },
  {
    label: 'Time',
    classes: 'text-capitalize nowrap word-break',
    sortable: true,
    align: 'left',
    name: 'time',
    field: 'time',
    style: 'width: 90px',
  },
  {
    label: 'Description',
    classes: 'text-capitalize nowrap',
    sortable: true,
    align: 'left',
    name: 'desc',
    field: 'desc',
    style: 'width: 294px',
    format: (t) => t || '-',
  },
  {
    label: 'Remark',
    classes: 'text-capitalize nowrap',
    sortable: true,
    align: 'left',
    name: 'remark',
    field: 'remark',
    style: 'width: 130px',
    format: (t) => t || '-',
  },
  {
    label: 'Location',
    classes: 'text-capitalize nowrap',
    sortable: true,
    align: 'left',
    name: 'location',
    field: 'location',
    style: 'width: 110px',
    format: (t) => t || '-',
  },
  {
    label: 'Room',
    classes: 'text-capitalize nowrap',
    sortable: true,
    align: 'right',
    name: 'room',
    field: 'room',
    style: 'width: 91px',
    format: (t) => t || '-',
  },
  {
    label: 'Exp',
    classes: 'text-capitalize nowrap',
    sortable: true,
    align: 'left',
    name: 'exp',
    field: 'exp',
    style: 'width: 90px',
    format: (t) => (t instanceof Date ? date.formatDate(t, 'YYYY/MM/DD') : '-'),
  },
  {
    label: 'User Init',
    classes: 'text-capitalize nowrap',
    sortable: true,
    align: 'right',
    name: 'userinit',
    field: 'userinit',
    style: 'width: 90px',
    format: (t) => t || '-',
  },
  {
    classes: 'text-capitalize nowrap',
    style: 'width: 3%',
    name: 'actions',
    field: 'actions',
  },
];
