import { TableHeader } from '~/components/VhpUI/typings';
export const tableHeaders: TableHeader[] = [
  {
    label: 'Date',
    field: 'datum',
    name: 'datum',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Storage',
    field: 'lager',
    name: 'lager',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Document Number',
    field: 'lscheinnr',
    name: 'lscheinnr',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Article',
    field: 'artnr',
    name: 'artnr',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Description',
    field: 'bezeich',
    name: 'bezeich',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Outgoing Quantity',
    field: 'out-qty',
    name: 'out-qty',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Average Price',
    field: 'avrg-price',
    name: 'avrg-price',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Amount',
    field: 'amount',
    name: 'amount',
    align: 'left',
    sortable: false,
  },
  {
    label: 'ID',
    field: 'id',
    align: 'left',
    name: 'id',
    sortable: false,
  },
  {
    label: 'Reason',
    field: 'reason',
    align: 'left',
    name: 'reason',
    sortable: false,
  },
];
