import { TableHeader } from '~/components/VhpUI/typings';

export const tableHeaders: TableHeader[] = [
  {
    label: 'Date',
    field: 'datum',
    name: 'datum',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Storage',
    field: 'lager ',
    name: 'lager ',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Supplier',
    field: 'lief',
    name: 'lief',
    sortable: false,
    align: 'left',
  },
  {
    label: 'Article Number',
    field: 'art',
    name: 'art',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Description',
    field: 'bezeich',
    name: 'bezeich',
    sortable: false,
    align: 'left',
  },
  {
    label: 'Delivery Unit',
    field: 'unit',
    name: 'unit',
    sortable: false,
    align: 'left',
  },
  {
    label: 'Price',
    field: 'epreis',
    name: 'epreis',
    sortable: false,
    align: 'right',
  },
  {
    label: 'Incoming Quantity',
    field: 'in-qty',
    name: 'in-qty',
    sortable: false,
    align: 'right',
  },
  {
    label: 'Amount',
    field: 'amount',
    name: 'amount',
    sortable: false,
    align: 'right',
  },
  {
    label: 'Document Number',
    field: 'docunr',
    name: 'docunr',
    sortable: false,
    align: 'left',
  },
  {
    label: 'Delivery Note',
    field: 'dlvnote',
    name: 'dlvnote',
    sortable: false,
    align: 'left',
  },
  {
    label: 'ID/Date/Time',
    field: 'note',
    name: 'note',
    sortable: false,
    align: 'left',
  },
  {
    label: 'Reason',
    field: 'reason',
    name: 'reason',
    sortable: false,
    align: 'left',
  },
  {
    label: 'Invoice Number',
    field: 'invnr',
    name: 'invnr',
    sortable: false,
    align: 'left',
  },
];
