import { TableHeader } from '~/components/VhpUI/typings';
export const tableHeaders: TableHeader[] = [
    {
        label: 'St',
        field: 'acct-fibukonto',
        name: 'acct-fibukonto',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Description',
        field: 'acct-fibukonto',
        name: 'acct-fibukonto',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Quantity',
        field: 'acct-fibukonto',
        name: 'acct-fibukonto',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Unit Price',
        field: 'acct-fibukonto',
        name: 'acct-fibukonto',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Amount',
        field: 'acct-fibukonto',
        name: 'acct-fibukonto',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Articel Number',
        field: 'acct-fibukonto',
        name: 'acct-fibukonto',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Type of Moving',
        field: 'acct-fibukonto',
        name: 'acct-fibukonto',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Created by',
        field: 'acct-fibukonto',
        name: 'acct-fibukonto',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Date',
        field: 'acct-fibukonto',
        name: 'acct-fibukonto',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Time',
        field: 'acct-fibukonto',
        name: 'acct-fibukonto',
        align: 'left',
        sortable: false,
    },
]