import { TableHeader } from '~/components/VhpUI/typings';


export const tableHeaders: TableHeader[] = [
    {
      label: 'ExtNo',
      name: 'ExtNo',
      field: 'nebenstelle',
      align: 'left',
      sortable: false,
    },
    {
      label: 'Date',
      name: 'date',
      field: 'datum',
      align: 'left',
      sortable: false,
    },
    {
      label: 'Time',
      name: 'time',
      field: 'zeit',
      align: 'left',
      sortable: false,
    },
    {
      label: 'Dialed Number',
      name: 'dialedNumber',
      field: 'rufnummer',
      align: 'left',
      sortable: false,
    },
    {
      label: 'Destination',
      name: 'destination',
      field: 'destination',
      align: 'left',
      sortable: false,
    },
    {
      label: 'PABX Rate',
      name: 'PABXrate',
      field: 'pabx-rate',
      align: 'left',
      sortable: false,
    },
    {
      label: 'Guest Rate',
      name: 'guestRate',
      field: 'guest-rate',
      align: 'left',
      sortable: false,
    },
    {
      label: 'Duration',
      name: 'duration',
      field: 'dauer',
      align: 'left',
      sortable: false,
    },
    {
      label: 'RmNo',
      name: 'rmno',
      field: 'nebenstelle',
      align: 'left',
      sortable: false,
    },
    {
      label: 'BillNo',
      name: 'billno',
      field: 'rechnr',
      align: 'left',
      sortable: false,
    },
    {
      label: 'Print',
      name: 'print',
      field: 'print',
      align: 'left',
      sortable: false,
    },
    {
      label: 'Pulse',
      name: 'pulse',
      field: 'impulse',
      align: 'left',
      sortable: false,
    },
    {
      label: 'Line',
      name: 'line',
      field: 'leitung',
      align: 'left',
      sortable: false,
    },
]