import { TableHeader } from '~/components/VhpUI/typings';
export const tableHeaders: TableHeader[] = [
  {
    label: 'Extension Number',
    field: 'ext',
    name: 'ext',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Date',
    field: 'datum',
    name: 'datum',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Time',
    field: 'zeit',
    name: 'zeit',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Dialed Number',
    field: 'dialed',
    name: 'dialed',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Destination',
    field: 'dest',
    name: 'dest',
    align: 'left',
    sortable: false,
  },
  {
    label: 'PABX Rate',
    field: 'pabx-rate',
    name: 'pabx-rate',
    align: 'right',
    sortable: false,
  },
  {
    label: 'Guest Rate',
    field: 'guest-rate',
    name: 'guest-rate',
    align: 'right',
    sortable: false,
  },
  {
    label: 'Duration',
    field: 'duration',
    name: 'duration',
    align: 'right',
    sortable: false,
  },
  {
    label: 'Room Number',
    field: 'zinr',
    name: 'zinr',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Pulse',
    field: 'pulse',
    name: 'pulse',
    align: 'right',
    sortable: false,
  },
  {
    label: 'Line',
    field: 'lin',
    name: 'lin',
    align: 'right',
    sortable: false,
  },
  {
    label: 'Printed',
    field: 'print',
    name: 'print',
    align: 'left',
    sortable: false,
  },
  {
    label: 'Reference Number',
    field: 'ref-no',
    name: 'ref-no',
    align: 'left',
    sortable: false,
  },
  {
    label: 'User Name',
    field: 'username ',
    name: 'username ',
    align: 'left',
    sortable: false,
  },
];

