import { TableHeader } from '~/components/VhpUI/typings';
export const tableHeaders: TableHeader[] = [
  {
    label: 'Department',
    field: 'dept',
    name: 'dept',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Name',
    field: 'name',
    name: 'name',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Phone Number',
    field: 'telephone',
    name: 'telephone',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Extention',
    field: 'ext',
    name: 'ext',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Mobile Number',
    field: 'mobil-telefon',
    name: 'mobil-telefon',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Facimile',
    field: 'fax',
    name: 'fax',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Address',
    field: 'adresse1',
    name: 'adresse1',
    align: 'right',
    sortable: true,
  },
  {
    label: 'City',
    field: 'wohnort',
    name: 'wohnort',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Zip',
    field: 'prefix',
    name: 'prefix',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Land',
    field: 'land',
    name: 'land',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Contact Person',
    field: 'vorname',
    name: 'vorname',
    align: 'right',
    sortable: true,
  },
  {
    label: 'Email',
    field: 'telex',
    name: 'telex',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Remark',
    field: 'adresse2',
    name: 'adresse2',
    align: 'left',
    sortable: true,
  },
  {
    label: 'ID',
    field: 'rec-id',
    name: 'rec-id',
    align: 'left',
    sortable: true,
  },
  { name: 'actions', field: 'actions' },

];

