import { TableHeader } from '~/components/VhpUI/typings';
export const tableHeaders: TableHeader[] = [
    {
        label: 'Bank Name',
        field: 'bankname',
        name: 'bankname',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Giro Number',
        field: 'gironum',
        name: 'GiroNumber',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Account Number',
        field: 'fibukonto',
        name: 'AccountNumber',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Giro Status',
        field: 'giro-status',
        name: 'GiroStatus',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Date',
        field: 'created',
        name: 'Date',
        align: 'left',
        sortable: false,
    },
    {
        label: 'ID',
        field: 'userinit',
        name: 'ID',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Date',
        field: 'changed',
        name: 'Date',
        align: 'left',
        sortable: false,
    },
    {
        label: 'ID',
        field: 'CID',
        name: 'ID',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Due Date',
        field: 'postedDate',
        name: 'DueDate',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Amount',
        field: 'betrag',
        name: 'Amount',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Document Number',
        field: 'DocumentNumber',
        name: 'DocumentNumber',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Clearing Date',
        field: 'ClearingDate',
        name: 'ClearingDate',
        align: 'left',
        sortable: false,
    },
    { name: 'actions', field: 'actions' },
]