import { TableHeader } from '~/components/VhpUI/typings';
export const tableHeaders: TableHeader[] = [
    {
        label: 'User Name',
        field: 'name',
        name: 'name',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Bill Number',
        field: 'rechnr',
        name: 'rechnr',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Cash (Local)',
        field: 'p-cash',
        name: 'p-cash',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Cash (Foreign)',
        field: 'f-cash',
        name: 'f-cash',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Currency',
        field: 'curr',
        name: 'curr',
        align: 'left',
        sortable: false,
    },
    {
        label: 'City Ledger',
        field: 'c-ledger',
        name: 'c-ledger',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Credit Card',
        field: 'creditcard',
        name: 'creditcard',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Room Number',
        field: 'zinr',
        name: 'zinr',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Guest Name',
        field: 'gname',
        name: 'gname',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Info',
        field: 'info',
        name: 'info',
        align: 'left',
        sortable: false,
    },
]

export const columns: TableHeader[] = [
    {
        label: 'Username',
        field: 'username',
        name: 'username',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Cash USD',
        field: 'usd',
        name: 'usd',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Cash Settlement',
        field: 'set',
        name: 'set',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Cash Deposit R',
        field: 'deposit',
        name: 'deposit',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Cash Deposit',
        field: 'deposit2',
        name: 'deposit2',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Money Exchange',
        field: 'ex1',
        name: 'ex1',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Money Exchange',
        field: 'ex2',
        name: 'ex2',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Money Exchange',
        field: 'ex3',
        name: 'ex3',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Total',
        field: 'total',
        name: 'total',
        align: 'right',
        sortable: false,
    },
]