import { TableHeader } from '~/components/VhpUI/typings';
export const tableHeaders: TableHeader[] = [
    {
        label: 'Departement',
        field: 'bezeich',
        name: 'bezeich',
        align: 'left',
        sortable: false,
    },
    {
        label: 'Cash',
        field: 'cash',
        name: 'cash',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Room / FO Bill',
        field: 'room',
        name: 'room',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Card',
        field: 'card',
        name: 'card',
        align: 'right',
        sortable: false,
    },
    {
        label: 'City Ledger',
        field: 'cl',
        name: 'cl',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Revenue',
        field: 'revenue',
        name: 'revenue',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Compliment',
        field: 'compli',
        name: 'compli',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Meal Coupon',
        field: 'mcoupon',
        name: 'mcoupon',
        align: 'right',
        sortable: false,
    },
    {
        label: 'Outstanding',
        field: 'gl',
        name: 'gl',
        align: 'right',
        sortable: false,
    },
]