import { TableHeader } from '~/components/VhpUI/typings';
import { date } from 'quasar';
import { formatterMoney } from '~/app/helpers/formatterMoney.helper';
import { formatTime } from '~/app/shared/helpers/utils';

export const detailBillColumns: TableHeader<any>[] = [
  {
    label: 'Article Number',
    field: 'articleNumber',
    name: 'articleNumber',
    classes: 'text-capitalize',
    headerStyle: 'width: 120px',
    align: 'right',
    sortable: true,
    style: 'width: 120px',
  },
  {
    label: 'Quantity',
    field: 'quantity',
    name: 'quantity',
    classes: 'text-capitalize',
    headerStyle: 'width: 120px',
    align: 'right',
    sortable: true,
    style: 'width: 120px',
  },
  {
    label: 'Description',
    field: 'description',
    name: 'description',
    classes: 'text-capitalize',
    headerStyle: 'width: 120px',
    align: 'left',
    sortable: true,
    style: 'width: 120px',
  },
  {
    label: 'Price',
    field: 'price',
    name: 'price',
    classes: 'text-capitalize',
    format: (v) => (Number.isInteger(v) ? formatterMoney(v) : ''),
    headerStyle: 'width: 120px',
    align: 'right',
    sortable: true,
    style: 'width: 120px',
  },
  {
    label: 'Amount',
    field: 'amount',
    name: 'amount',
    classes: 'text-capitalize',
    format: (v) => (Number.isInteger(v) ? formatterMoney(v) : ''),
    headerStyle: 'width: 120px',
    align: 'right',
    sortable: true,
    style: 'width: 120px',
  },
  {
    label: 'Room Number',
    field: 'roomNumber',
    name: 'roomNumber',
    classes: 'text-capitalize',
    headerStyle: 'width: 120px',
    align: 'right',
    sortable: true,
    style: 'width: 120px',
  },
  {
    label: 'Bill Date',
    field: 'billDate',
    name: 'billDate',
    format: (v) => (v instanceof Date ? date.formatDate(v, 'DD/MM/YY') : ''),
    classes: 'text-capitalize',
    headerStyle: 'width: 120px',
    align: 'right',
    sortable: true,
    style: 'width: 120px',
  },
  {
    label: 'User Id',
    field: 'userId',
    name: 'userId',
    classes: 'text-capitalize',
    headerStyle: 'width: 120px',
    align: 'right',
    sortable: true,
    style: 'width: 120px',
  },
  {
    label: 'System Date',
    field: 'systemDate',
    name: 'systemDate',
    format: (v) => (v instanceof Date ? date.formatDate(v, 'DD/MM/YY') : ''),
    classes: 'text-capitalize',
    headerStyle: 'width: 120px',
    align: 'right',
    sortable: true,
    style: 'width: 120px',
  },
  {
    label: 'Time',
    field: 'time',
    name: 'time',
    classes: 'text-capitalize',
    headerStyle: 'width: 120px',
    align: 'right',
    sortable: true,
    style: 'width: 120px',
    format: (v) => (Number.isInteger(v) ? formatTime(v) : ''),
  },
];
