import { TableHeader } from '~/components/VhpUI/typings';
import { formatterMoney } from '~/app/helpers/formatterMoney.helper';
import { formatToBL } from '~/app/helpers/formatterDate.helper';
import { displayTime } from '~/app/helpers/displayTime.helper';
export const journalizingColumns: TableHeader<any>[] = [
  {
    label: 'Account Number',
    field: 'account_number',
    name: 'account_number',
    classes: 'text-capitalize',
    headerStyle: 'width: 120px',
    style: 'width: 120px',
    sortable: true,
    align: 'left',
  },
  {
    label: 'Account Name',
    field: 'description',
    name: 'description',
    classes: ' text-capitalize',
    headerStyle: 'width: 260px',
    style: 'width: 260px',
    sortable: true,
    align: 'left',
  },

  {
    label: 'Debit',
    field: 'debit',
    name: 'debit',
    format: (it) => formatterMoney(it),
    classes: ' text-capitalize',
    headerStyle: 'width: 150px',
    style: 'width: 150px',
    sortable: true,
    align: 'right',
  },
  {
    label: 'Credit',
    field: 'credit',
    name: 'credit',
    format: (it) => formatterMoney(it),
    classes: 'nowrap pointer text-capitalize',
    headerStyle: 'width: 150px',
    style: 'width: 150px',
    sortable: true,
    align: 'right',
  },
  {
    label: 'Remark',
    field: 'remark',
    name: 'remark',
    classes: 'nowrap pointer text-capitalize',
    headerStyle: 'width: 185px',
    style: 'width: 185px',
    sortable: true,
    align: 'left',
  },

  {
    label: 'Created ID',
    field: 'user_id',
    name: 'user_id',
    classes: 'nowrap pointer text-capitalize',
    headerStyle: 'width: 100px',
    style: 'width: 100px',
    sortable: true,
    align: 'left',
  },
  {
    label: 'Created Date',
    field: 'created_date',
    format: (it) => formatToBL(it),
    name: 'created_date',
    classes: 'nowrap pointer text-capitalize',
    headerStyle: 'width: 115px',
    style: 'width: 115px',
    sortable: true,
    align: 'left',
  },

  {
    label: 'Created Time',
    field: 'time',
    name: 'time',
    format: (it) => displayTime(it),
    classes: 'nowrap pointer text-capitalize',
    headerStyle: 'width: 115px',
    style: 'width: 115px',
    sortable: true,
    align: 'left',
  },

  {
    label: 'Changed ID',
    field: 'changed_id',
    name: 'changed_id',
    classes: 'nowrap pointer text-capitalize',
    headerStyle: 'width: 110px',
    style: 'width: 110px',
    sortable: true,
    align: 'left',
  },
  {
    label: 'Changed Date',
    field: 'changed_date',
    name: 'changed_date',
    format: (it) => formatToBL(it),
    classes: 'nowrap pointer text-capitalize',
    headerStyle: 'width: 120px',
    style: 'width: 120px',
    sortable: true,
    align: 'left',
  },
];
