import { TableHeader } from '~/components/VhpUI/typings';

export const columns: TableHeader<any>[] = [
  {
    label: 'Date',
    name: 'date',
    field: 'date',
    classes: ' text-capitalize',
    headerStyle: 'width: 80px; text-align: left;',
    style: 'width: 80px',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Table Number',
    name: 'tb_no',
    field: 'tb_no',
    classes: ' text-capitalize',
    headerStyle: 'width: 100px; text-align: left;',
    style: 'width: 100px',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Bill Number',
    name: 'bill_no',
    field: 'bill_no',
    classes: ' text-capitalize',
    headerStyle: 'width: 100px; text-align: left;',
    style: 'width: 100px',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Article Number',
    name: 'art_no',
    field: 'art_no',
    classes: ' text-capitalize',
    headerStyle: 'width: 100px; text-align: left;',
    style: 'width: 100px',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Description',
    name: 'description',
    field: 'description',
    classes: ' text-capitalize',
    headerStyle: 'width: 200px; text-align: left;',
    style: 'width: 200px',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Outlet',
    name: 'department',
    field: 'department',
    classes: ' text-capitalize',
    headerStyle: 'width: 175px; text-align: left;',
    style: 'width: 175px',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Quantity',
    name: 'qty',
    field: 'qty',
    classes: ' text-capitalize',
    headerStyle: 'width: 100px; text-align: left;',
    style: 'width: 100px',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Amount',
    name: 'amount',
    field: 'amount',
    classes: ' text-capitalize',
    headerStyle: 'width: 125px; text-align: left;',
    style: 'width: 125px',
    sortable: true,
    align: 'right',
  },
  {
    label: 'Time',
    name: 'time',
    field: 'time',
    classes: ' text-capitalize',
    headerStyle: 'width: 75px; text-align: left;',
    style: 'width: 75px',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Id',
    name: 'id',
    field: 'id',
    classes: ' text-capitalize',
    headerStyle: 'width: 50px; text-align: left;',
    style: 'width: 50px',
    align: 'left',
    sortable: true,
  },
];
