import { date } from 'quasar';
import { TableHeader } from '~/components/VhpUI/typings';
import { ResPaymentDebtPayList } from '../models/payment.model';
import { formatterMoney } from '~/app/helpers/formatterMoney.helper';

export const paymentListColumns: TableHeader<ResPaymentDebtPayList>[] = [
  {
    label: 'Bill Receiver',
    field: 'billName',
    name: 'billname',
    align: 'left',
    sortable: true,
    style: 'width: 250px',
    headerStyle: 'width: 250px',
  },
  {
    label: 'Bill Number',
    field: 'billNumber',
    name: 'rechnr',
    align: 'right',
    sortable: true,
    style: 'width: 115px',
    headerStyle: 'width: 115px',
  },
  {
    label: 'By Date',
    field: 'billDate',
    name: 'rgdatum',
    format: (v) => (v instanceof Date ? date.formatDate(v, 'DD/MM/YY') : ''),
    align: 'left',
    sortable: true,
    style: 'width: 100px',
    headerStyle: 'width: 100px',
  },
  {
    label: 'Debt Amount',
    field: 'arAmount',
    name: 'debt',
    align: 'right',
    format: (v) => (!Number.isNaN(v) ? formatterMoney(v) : ''),
    sortable: true,
    style: 'width: 140px',
    headerStyle: 'width: 140px',
  },
  {
    label: 'Payment Amount',
    field: 'paymentAmount',
    name: 'tot-debt',
    align: 'right',
    sortable: true,
    format: (v) => (!Number.isNaN(v) ? formatterMoney(v) : ''),
    style: 'width: 140px',
    headerStyle: 'width: 140px',
  },
  {
    label: 'Balance',
    field: 'balance',
    format: (v) => (!Number.isNaN(v) ? formatterMoney(v) : ''),
    name: 'credit',
    align: 'right',
    sortable: true,
    style: 'width: 140px',
    headerStyle: 'width: 140px',
  },
  {
    label: 'Reference Number',
    field: 'referenceNumber',
    name: 'refno',
    align: 'right',
    sortable: true,
    style: 'width: 115px',
    headerStyle: 'width: 115px',
  },
  {
    label: 'Remark',
    field: 'remark',
    name: 'remarks',
    align: 'left',
    sortable: true,
    style: 'width: 285px',
    headerStyle: 'width: 285px',
  },
  {
    label: 'Room Number',
    field: 'roomNumber',
    name: 'zinr',
    align: 'left',
    sortable: true,
    style: 'width: 115px',
    headerStyle: 'width: 115px',
  },
  {
    label: 'Id',
    field: 'id',
    name: 'user-init',
    align: 'left',
    sortable: true,
    style: 'width: 100px',
    headerStyle: 'width: 100px',
  },
  {
    label: 'Guest Name',
    field: 'guestName',
    name: 'gastname',
    align: 'left',
    sortable: true,
    style: 'width: 215px',
    headerStyle: 'width: 215px',
  },
  {
    label: 'Foreign Amount',
    field: 'arForeignAmount',
    name: 'debt-foreign',
    format: (v) => (!Number.isNaN(v) ? formatterMoney(v) : ''),
    align: 'right',
    sortable: true,
    style: 'width: 140px',
    headerStyle: 'width: 140px',
  },
  {
    label: 'Currency',
    field: 'currency',
    name: 'currency',
    align: 'left',
    sortable: true,
    style: 'width: 100px',
    headerStyle: 'width: 100px',
  },
  {
    label: 'Voucher Number',
    field: 'voucherNumber',
    name: 'vouc-nr',
    align: 'left',
    sortable: true,
    style: 'width: 120px',
    headerStyle: 'width: 120px',
  },
];
