import { TableHeader } from '~/components/VhpUI/typings';
import { ResSoaList } from '../models/soa-list.model';

export const soaListColumns: TableHeader<ResSoaList>[] = [
  {
    label: 'Date',
    field: 'printdate',
    name: 'printdate',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Outlet',
    field: (row) => (row.outlet ? 'Yes' : 'No'),
    name: 'outlet',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Guest Name',
    field: 'name',
    name: 'name',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Billing Number',
    field: 'rechnr',
    name: 'rechnr',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Debit',
    field: 'debt',
    name: 'debt',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Credit',
    field: 'credit',
    name: 'credit',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Balance',
    field: 'tot-balance',
    name: 'tot-balance',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Reference',
    field: 'voucherNo',
    name: 'voucherNo',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Foreign Debit',
    field: 'fdebt',
    name: 'fdebt',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Foreign Credit',
    field: 'fcredit',
    name: 'fcredit',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Foreign',
    field: 'fsaldo',
    name: 'fsaldo',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Remark',
    field: 'remarks',
    name: 'remarks',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Invoice Number',
    field: (row) => row['inv-str'],
    name: 'invoice_number',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Printed',
    field: (row) => (row.printed ? 'Yes' : 'No'),
    name: 'printed',
    align: 'left',
    sortable: true,
  },
  {
    label: 'Selected',
    field: (row) => (row.selected ? 'Yes' : 'No'),
    name: 'selected',
    align: 'left',
    sortable: true,
  },
];
