import { TableHeader } from '~/components/VhpUI/typings';
import { formatterMoney } from '~/app/helpers/formatterMoney.helper';
import { formatToBL } from '~/app/helpers/formatterDate.helper';
export const transactionColumns: TableHeader<any>[] = [
  {
    label: 'Bill Name',
    field: 'billName',
    name: 'bill_name',
    sortable: true,
  },
  {
    label: 'Room Number',
    field: 'roomNumber',
    name: 'room_number',
    sortable: true,
  },
  {
    label: 'Bill Number',
    field: 'billNumber',
    name: 'bill_number',
    sortable: true,
    align: 'right',
  },
  {
    label: 'Bill Date',
    field: 'billDate',
    name: 'bill_date',
    format: (it) => formatToBL(it),
    sortable: true,
  },
  {
    label: 'Debt Amount',
    field: 'debtAmount',
    name: 'debt_amount',
    format: (it) => formatterMoney(it),
    sortable: true,
    align: 'right',
  },
  {
    label: 'Pay Amount',
    field: 'payAmount',
    name: 'pay_amount',
    format: (it) => formatterMoney(it),
    sortable: true,
    align: 'right',
  },
  {
    label: 'Balance',
    field: 'balance',
    format: (it) => formatterMoney(it),
    name: 'balance',
    sortable: true,
    align: 'right',
  },
  {
    label: 'Ref Number',
    field: 'refNumber',
    name: 'ref_no',
    sortable: true,
  },
  {
    label: 'Counter Number',
    field: 'counterNumber',
    name: 'counter_no',
    sortable: true,
  },
  {
    label: 'Pay Date',
    format: (it) => formatToBL(it),
    field: 'payDate',
    name: 'pay_date',
    sortable: true,
  },
  {
    label: 'Payment',
    field: 'payment',
    name: 'payment',
    sortable: true,
  },
  {
    label: 'Id',
    field: 'id',
    name: 'ID',
    sortable: true,
  },
  {
    label: 'Currency',
    field: 'currency',
    name: 'currency',
    sortable: true,
  },
  {
    label: 'Guest Name',
    field: 'guestName',
    name: 'guest_name',
    sortable: true,
  },
  {
    label: 'Voucher Number',
    field: 'voucherNumber',
    name: 'voucher_number',
    sortable: true,
  },
  {
    label: 'Arrival',
    field: 'arrival',
    name: 'arrival',
    sortable: true,
  },
  {
    label: 'Departure',
    field: 'departure',
    name: 'departure',
    sortable: true,
  },
  {
    label: 'Stay',
    field: 'stay',
    name: 'stay',
    sortable: true,
  },
  {
    label: 'Foreign Amount',
    field: 'foreignAmount',
    name: 'foreign_amount',
    format: (it) => formatterMoney(it),
    sortable: true,
  },
  {
    label: 'Remark',
    field: 'remark',
    name: 'remark',
    sortable: true,
  },
  { name: 'actions', field: 'actions' },
];
